ServiceHost/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        public ProductCategorySearchModel SearchModel;
        public List<ProductCategoryViewModel> ProductCategories;
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var result = _productCategoryApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("Edit", productCategory);
        }

        public JsonResult OnPostEdit(EditProductCategory command)
        {

            var result = _productCategoryApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductPicture;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductPictures
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public ProductPictureSearchModel SearchModel;
        public List<ProductPictureViewModel> ProductPictures;
        public SelectList Products;
        private readonly IProductApplication _productApplication;
        private readonly IProductPictureApplication _productPictureApplication;
        public IndexModel(IProductApplication productApplication, IProductPictureApplication productPictureApplication)
        {
            _productApplication = productApplication;
            _productPictureApplication = productPictureApplication;
        }
        public void OnGet(ProductPictureSearchModel searchModel)
        {
            Products = new SelectList(_productApplication.GetProducts(), "Id", "Name");
            ProductPictures = _productPictureApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProductPicture()
            {
                Products = _productApplication.GetProducts()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProductPicture command)
        {
            var result = _productPictureApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productPicture = _productPictureApplication.GetDetails(id);
            productPicture.Products = _productApplication.GetProducts();
            return Partial("Edit", productPicture);
        }

        public JsonResult OnPostEdit(EditProductPicture command)
        {
            var result = _productPictureApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetRemove(long id)
        {
            var result = _productPictureApplication.Remove(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");
            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetRestore(long id)
        {
            var result = _productPictureApplication.Restore(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");
            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/Slides/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductPicture;
using ShopManagement.Application.Contracts.Slide;

namespace ServiceHost.Areas.Administration.Pages.Shop.Slides
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<SlideViewModel> Slides;
        private readonly ISlideApplication _slideApplication;

        public IndexModel(ISlideApplication slideApplication)
        {
            _slideApplication = slideApplication;
        }
        public void OnGet()
        {
            Slides = _slideApplication.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateSlide();
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateSlide command)
        {
            var result = _slideApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var slide = _slideApplication.GetDetails(id);
            return Partial("Edit", slide);
        }

        public JsonResult OnPostEdit(EditSlide command)
        {
            var result = _slideApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetRemove(long id)
        {
            var result = _slideApplication.Remove(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");
            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetRestore(long id)
        {
            var result = _slideApplication.Restore(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");
            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Create.cshtml
@model ShopManagement.Application.Contracts.ProductPicture.CreateProductPicture
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد محصول جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصول</label>
                    <select class="form-control" asp-for="ProductId"
                            asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="0">محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Edit.cshtml
@model ShopManagement.Application.Contracts.ProductPicture.EditProductPicture
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش محصول جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصول</label>
                    <select class="form-control" asp-for="ProductId"
                            asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="0">محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Shop.ProductPictures.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت عکس محصولات";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد عکس محصول جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در عکس محصولات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="Model.Products">
                            <option value="0">محصول ...</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست عکس محصولات</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام محصول</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ProductPictures)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/ProductPictures/@item.Picture" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Product</td>
                                        <td class="text-center">
                                            @if (!item.IsRemoved)
                                            {
                                                <i class="fa fa-check fa-3x text-success"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-remove fa-3x text-danger"></i>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            @if (!item.IsRemoved)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id"
                                                   class="btn btn-danger waves-effect waves-light m-b-5">حذف</a>
                                            }
                                            else
                                            {
                                                <a asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id"
                                                   class="btn btn-success waves-effect waves-light m-b-5">فعال سازی</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}